version: '3.6'
services:
  py:
    build: 
      context: .
      dockerfile: DockerfilePY
 #   command: python3
    entrypoint: python3 /ext/app.py    
    restart: always
    ports:
      - 8050:8050
      - 5000:5000

    volumes:
      - ./:/ext